### PR TITLE
version to allow horizontal drag

### PR DESCRIPTION
**Pull request by boeledi**
Second modification, the Widget

### CODE REVIEW

**Comment by Norbert515** [comment]
Sorry for the delay, looks good. I'll test it out later today

**Comment by Norbert515** [comment]
Hey, I had a problem with the imports "import '../helpers/my_draggable.dart';". I can't seem to find the helpers folder.
 I merged it into a different branch for now.

**Comment by boeledi** [comment]
my bad...  change the import statement to "import 'my_draggable.dart'.  This comes from my own project.

**Comment by Norbert515** [comment]
could you open a new PR with that change?

**Pull request merged**
